name: just_the_tooltip
description: A multi directional tooltip used to display any content with
  inbuilt support for list views
version: 0.0.11+3
homepage: https://github.com/quentin-parmentier/just_the_tooltip_fork

environment:
  sdk: ">=2.12.0 <=3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  golden_toolkit: ^0.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
